
import { Link } from 'react-router-dom';
import { Button } from '@/components/ui/button';
import Header from '@/components/Header';
import Footer from '@/components/Footer';
import SEO from '@/components/SEO';
import { builderAsset } from './assets';
import thumbBox from './media/box.webp';import thumbCorner from './media/corner.webp';import thumbCurved from './media/curved.webp';import thumbHood from './media/hood.webp';import thumbLouvered from './media/louvered.webp';import thumbModular from './media/modular.webp';import thumbRound from './media/round.webp';import thumbTapered from './media/tapered.webp';
const profileThumbs:Record<Profile,string>={box:thumbBox,corner:thumbCorner,curved:thumbCurved,hood:thumbHood,louvered:thumbLouvered,modular:thumbModular,round:thumbRound,tapered:thumbTapered};
import './shroud-builder.css';
import {useCallback,useEffect,useRef,useState} from 'react';
import {Box, RotateCcw, Download, Printer, Ruler, Move3d, ArrowUpRight, Check, ChevronRight, Maximize, Layers, Info, PanelTop, Sun, FileText} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {RadioGroup,RadioGroupItem} from '@/components/ui/radio-group';
import {Switch} from '@/components/ui/switch';
import ShroudView, {ViewMode} from './shroud-view';
import Elevation from './elevation';
import {Config,Profile,initial,products,palette,measurements,limits,validate,selectProfile,hoodStiffenerLayout,HOOD_MIN_WIDTH,finishSpecification,updateConfiguration,minimumArchRadius,archContour,MAX_ARCH_RADIUS,hasPanelOptions,includedPanels,panelDescription,maximumArchWidth,fallDescription} from './shroud-model';
import {flangeFixingLayout} from './installation-layout';
const fmt=(n:number)=>n.toLocaleString('en-AU',{maximumFractionDigits:1});
function NumberField({label,value,onChange,help,min=50,max=6000,step=1}:{label:string;value:number;onChange:(v:number)=>void;help?:string;min?:number;max?:number;step?:number}){
 const [draft,setDraft]=useState(String(value));useEffect(()=>setDraft(String(value)),[value]);const invalid=draft===''||!Number.isFinite(Number(draft))||Number(draft)<min||Number(draft)>max;
 return <label className="number-field"><span>{label}</span><div className={invalid?'number-input invalid':'number-input'}><input type="number" aria-label={label} aria-invalid={invalid} inputMode="decimal" min={min} max={max} step={step} value={draft} onChange={e=>{setDraft(e.target.value);const n=Number(e.target.value);if(e.target.value!==''&&Number.isFinite(n)&&n>=min&&n<=max)onChange(n);}} onBlur={()=>{if(invalid)setDraft(String(value));}}/><span>{label.includes('angle')?'°':'mm'}</span></div>{invalid?<small className="field-error">Enter {min}–{max}. Last valid value is shown.</small>:help&&<small>{help}</small>}</label>;
}
export default function ShroudBuilder(){
 const [c,setC]=useState<Config>(initial);const [tab,setTab]=useState('3d');const [view,setView]=useState<ViewMode>('perspective');const [showWindow,setShowWindow]=useState(true);const [showStudWall,setShowStudWall]=useState(true);const [showScrews,setShowScrews]=useState(true);const [dimensions,setDimensions]=useState(true);const [reset,setReset]=useState(0);const [notice,setNotice]=useState('');const [downloading,setDownloading]=useState(false);const [webgl,setWebgl]=useState(true);const stage=useRef<HTMLDivElement>(null);const latest=useRef(c);latest.current=c;
 const update=(patch:Partial<Config>)=>setC(old=>updateConfiguration(old,patch));const product=products.find(p=>p.id===c.profile)!;const m=measurements(c),range=limits(c),errors=validate(c);const safe=errors.length?initial:c;const ribs=hoodStiffenerLayout(c.width);const fixings=flangeFixingLayout(c);const finishSpec=finishSpecification(c);const selectedColour=palette.find(p=>p.hex===c.colour)!;const customColour=Boolean(c.otherColour.trim());
 const onReady=useCallback((ok:boolean)=>setWebgl(ok),[]);
 const changeProduct=(p:Profile)=>{setC(old=>selectProfile(old,p));setView('perspective');};
 const panels=includedPanels(c);
 const summary={...(hasPanelOptions(c.profile)?{topPanel:'Included',leftPanel:panels.left?'Included':'Omitted',bottomPanel:panels.bottom?'Included':'Omitted',rightPanel:panels.right?'Included':'Omitted',...(c.profile==='corner'?{panelOrientation:'Left: face A end; right: return B end; bottom: both faces'}:{})}:{}),product:`ThermaCore ${product.title}`,reference:c.reference,internalDiameterMm:c.profile==='round'?c.width:null,internalWidthMm:c.profile==='round'?null:c.width,internalHeightMm:c.profile==='hood'||c.profile==='round'?null:c.height,windowReferenceHeightMm:c.profile==='hood'?c.height:null,depthMm:c.depth,materialThicknessMm:6,drainageFall:fallDescription(c),fixingFlangeMm:c.flange,previewFixingCount:fixings.points.length,previewMaxFixingCentresMm:Number(fixings.maxPitch.toFixed(1)),...finishSpec,...(c.profile==='corner'?{returnInternalWidthMm:c.returnWidth}:{}),...(c.profile==='tapered'?{sillDepthMm:c.bottomDepth}:{}),...(['curved','round'].includes(c.profile)?{internalRadiusMm:c.internalRadius}:{}),...(c.roundedEnds?{roundedEnds:'Included — both front corners rounded'}:{}),...(c.profile==='hood'?{stiffenerCount:ribs.count,stiffenerThicknessMm:6,stiffenerRearHeightMm:c.stiffenerHeight,stiffenerEndOffsetMm:150,stiffenerEqualSpacingMm:Number(ribs.pitch.toFixed(3)),stiffenerCentresFromLeftMm:ribs.positions.map(v=>Number(v.toFixed(3))).join(', '),stiffenerShape:'Triangular, above canopy; taper from rear height to zero at front',...(c.hoodCorner?{cornerCanopy:c.hoodCornerRounded?'Included (rounded corner)':'Included (square corner)',cornerReturnLengthMm:c.returnWidth}:{cornerCanopy:'None'})}:{}),...(c.profile==='louvered'?{bladePitchMm:c.bladePitch,bladeAngleDegrees:c.bladeAngle}:{}),note:'Nominal configuration. Fixings, drainage falls, joints and final fabrication details to be confirmed by AWS.'};
 const download=async()=>{if(errors.length||downloading)return;setDownloading(true);try{const [{downloadConfigurationPdf},{capturePerspective}]=await Promise.all([import('./configuration-pdf'),import('./perspective-export')]);const perspective=await capturePerspective(c,{windowVisible:showWindow,studWallVisible:showStudWall,screwsVisible:showScrews});await downloadConfigurationPdf(c,perspective);setNotice('PDF configuration downloaded.');}catch(error){console.error('Configuration PDF export failed',error);setNotice('The PDF could not be created. Please try again.');}finally{setDownloading(false);}};
 useEffect(()=>{if(notice){const t=setTimeout(()=>setNotice(''),3500);return()=>clearTimeout(t);}},[notice]);
 useEffect(()=>{
 type Tool={name:string;description:string;inputSchema:unknown;annotations:{readOnlyHint:boolean};execute:(input:unknown)=>unknown};
 const context=(document as unknown as {modelContext?:{registerTool:(tool:Tool,options:{signal:AbortSignal})=>Promise<void>|void}}).modelContext;if(!context?.registerTool)return;const controller=new AbortController();
 const specs={leftPanel:{type:'boolean'},bottomPanel:{type:'boolean'},rightPanel:{type:'boolean'},profile:{type:'string',enum:products.map(p=>p.id)},width:{type:'number',minimum:50,maximum:6000},height:{type:'number',minimum:50,maximum:6000},internalRadius:{type:'number',minimum:25,maximum:MAX_ARCH_RADIUS},depth:{type:'number',minimum:50,maximum:850},returnWidth:{type:'number',minimum:50,maximum:6000},bottomDepth:{type:'number',minimum:50,maximum:850},flange:{type:'number',enum:[0,50,100]},stiffenerHeight:{type:'number',minimum:6,maximum:300},hoodCorner:{type:'boolean'},roundedEnds:{type:'boolean'}};
 const tools:Tool[]=[{name:'read_shroud_configuration',description:'Read the current shroud dimensions and material thickness in mm.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({...latest.current,materialThickness:6,validation:validate(latest.current)})},{name:'configure_shroud',description:'Update the visible shroud preview. Width and height are internal clear dimensions in mm; for a round shroud, internalRadius sets diameter (width and height) to twice the radius. Profile curved is Arch Shroud: internalRadius changes the arch while retaining width and overall height, and must span the opening. Width and height edits never change the arch radius; invalid combinations are rejected. Arch sides are always included and only bottomPanel can be toggled. For box, corner and tapered profiles, leftPanel, bottomPanel and rightPanel toggle individual plates and their fixings; the top remains. For corner, left is the face A end, right is the return B end, and bottom spans both. Depth is the projection. Hood stiffeners are automatic at 150 mm end centres and equal spacing up to 450 mm. Does not order or submit anything.',inputSchema:{type:'object',properties:specs,additionalProperties:false},annotations:{readOnlyHint:false},execute:async(input)=>{if(!input||typeof input!=='object'||Array.isArray(input))throw new Error('Expected an object.');const patch=input as Partial<Config>;for(const key of Object.keys(patch)){if(!(key in specs))throw new Error(`Unknown setting ${key}.`);if(['leftPanel','bottomPanel','rightPanel','hoodCorner','roundedEnds'].includes(key)){if(typeof patch[key as keyof Config]!=='boolean')throw new Error('Panel selections must be booleans.');}else if(key!=='profile'&&typeof patch[key as keyof Config]!=='number')throw new Error('Dimensions must be numbers.');}const base=patch.profile?selectProfile(latest.current,patch.profile):latest.current;if(base.profile==='curved'&&(patch.leftPanel===false||patch.rightPanel===false))throw new Error('Arch shrouds always include both side panels.');if(base.profile==='round'){if(patch.width!==undefined&&patch.height!==undefined&&patch.width!==patch.height)throw new Error('Round width and height must match.');if(patch.internalRadius!==undefined&&((patch.width!==undefined&&Math.abs(patch.width-patch.internalRadius*2)>0.0001)||(patch.height!==undefined&&Math.abs(patch.height-patch.internalRadius*2)>0.0001)))throw new Error('Round diameter must equal twice the internal radius.');}const next=updateConfiguration(base,patch);const problems=validate(next);if(problems.length)throw new Error(problems.join(' '));setC(next);latest.current=next;await new Promise<void>(resolve=>requestAnimationFrame(()=>requestAnimationFrame(()=>resolve())));return {...next,materialThickness:6};}}];
 for(const tool of tools){try{void Promise.resolve(context.registerTool(tool,{signal:controller.signal})).catch(()=>{});}catch{}}
 return()=>controller.abort();
 },[]);
   return <><SEO title="Design Your Window Shroud in 3D | Aus Window Shrouds" description="Design a custom ThermaCore© window shroud online. Choose dimensions and finishes, preview it in 3D, then request a quote fast." canonicalPath="/shroud-builder" /><Header /><div className="shroud-builder">
 <main className="app-main"><div className="page-heading"><div><div className="eyebrow">THERMACORE COLLECTION CONFIGURATOR</div><h1>Shroud builder</h1><p>Choose a profile. Set your internal dimensions. See it in 3D.</p></div><div className="heading-actions"><Button variant="outline" className="button secondary" onClick={()=>{setC(initial);setShowStudWall(true);setShowScrews(true);setView('perspective');setReset(r=>r+1);setNotice('Default design restored.');}}><RotateCcw size={16}/>Reset</Button><Button className="button dark" onClick={()=>window.print()} disabled={!!errors.length}><Printer size={16}/>Print specification</Button></div></div>
 <div className="workspace"><aside className="controls-panel"><section className="control-section"><div className="section-title"><span className="step">01</span><h2>Choose your profile</h2><span className="count">{products.length} profiles</span></div>
 <RadioGroup value={c.profile} onValueChange={v=>changeProduct(v as Profile)} className="product-grid" aria-label="Shroud profile">{products.map(p=><label key={p.id} className={`product-card ${c.profile===p.id?'selected':''}`}><RadioGroupItem value={p.id} className="profile-radio"/><img src={profileThumbs[p.id]} alt=""/><span>{p.name}</span>{c.profile===p.id&&<Check size={14} className="product-check"/>}</label>)}</RadioGroup>
 <p className="product-description">{product.description}</p>
 {hasPanelOptions(c.profile)&&<div className="panel-options"><h3>Panels</h3><div className={`panel-switches ${c.profile==='curved'?'single-panel':''}`}>{(c.profile==='curved'?(['bottom'] as const):(['left','bottom','right'] as const)).map(side=><label key={side}><span>{side[0].toUpperCase()+side.slice(1)}</span><Switch aria-label={`${side[0].toUpperCase()+side.slice(1)} panel`} checked={panels[side]} onCheckedChange={v=>update({[`${side}Panel`]:v})}/></label>)}</div><p>{c.profile==='curved'?'The arch and both sides are always included.':c.profile==='corner'?'Left: face A end. Right: return B end. Bottom: both faces. Top always included.':'Sides are viewed from outside. Top always included.'}</p></div>}
 </section>
 <section className="control-section"><div className="section-title"><span className="step">02</span><h2>Set the dimensions</h2><span className="unit-badge">mm</span></div><div className="measurement-note"><Ruler size={17}/><span>Enter <strong>internal measurements.</strong><br/>We add the 6 mm material outside.</span></div>
 {c.profile==='round'?<><div className="field-grid"><NumberField label="Internal radius" value={c.internalRadius} min={25} max={3000} step={0.5} onChange={v=>update({internalRadius:v})}/><NumberField label="Internal diameter" value={c.width} onChange={v=>update({width:v})}/></div><p className="inline-note">Diameter = 2 × radius. Either measurement updates the other. The outside diameter is 12 mm larger.</p></>:<div className="field-grid"><NumberField label={c.profile==='corner'?'Internal width A':c.profile==='hood'?'Clear canopy span':'Internal width'} value={c.width} min={c.profile==='hood'?HOOD_MIN_WIDTH:50} max={c.profile==='curved'?Math.floor(Math.min(6000,maximumArchWidth(c.internalRadius,c.height))*10)/10:6000} onChange={v=>update({width:v})}/><NumberField label={c.profile==='hood'?'Window height (reference)':'Internal height'} value={c.height} min={c.profile==='curved'?Math.max(50,Math.ceil(archContour(c).rise*10)/10):50} onChange={v=>update({height:v})}/></div>}
 {c.profile==='curved'&&<><NumberField label="Internal radius" value={c.internalRadius} min={minimumArchRadius(c.width,c.height)} max={MAX_ARCH_RADIUS} step={1} onChange={v=>update({internalRadius:v})} help={`Minimum ${fmt(minimumArchRadius(c.width,c.height))} mm for this opening. A larger radius makes a flatter arch; width and overall height stay fixed.`}/><p className="inline-note">Arch rise {fmt(archContour(c).rise)} mm · straight jamb height {fmt(archContour(c).springY)} mm. Radius stays fixed when width or height changes. Change the radius yourself if the opening needs a flatter arch.</p></>}

 {c.profile==='corner'&&<NumberField label="Internal return width B" value={c.returnWidth} onChange={v=>update({returnWidth:v})} help="Each leg is measured to the internal 90° corner."/>}
 {c.profile==='hood'&&<div className="panel-options"><h3>Corner canopy</h3><div className="panel-switches single-panel"><label><span>Wrap a 90° corner</span><Switch aria-label="Corner canopy" checked={!!c.hoodCorner} onCheckedChange={v=>update({hoodCorner:v})}/></label><label><span>Rounded corner</span><Switch aria-label="Rounded corner" checked={!!c.hoodCornerRounded} onCheckedChange={v=>update(v?{hoodCornerRounded:true,hoodCorner:true}:{hoodCornerRounded:false})}/></label></div>{c.hoodCorner&&<NumberField label="Corner return length" value={c.returnWidth} min={50} max={6000} onChange={v=>update({returnWidth:v})} help="Length of the canopy leg returning along the side wall, measured from the internal corner."/>}</div>}
 {c.profile==='hood'&&<div className="panel-options"><h3>Ends</h3><div className="panel-switches single-panel"><label><span>Rounded ends</span><Switch aria-label="Rounded ends" checked={!!c.roundedEnds} onCheckedChange={v=>update({roundedEnds:v})}/></label></div><p>Rounds off both front corners of the canopy.</p></div>
 <NumberField label={c.profile==='tapered'?'Head depth':'Projection depth'} value={c.depth} min={range.min} max={range.max} onChange={v=>update({depth:v,bottomDepth:Math.min(c.bottomDepth,v)})} help={`Custom ${range.min}–${range.max} mm · rear fixing plane to front edge.`}/>
 <RadioGroup className="depth-presets" aria-label="Standard depth" value={String(c.depth)} onValueChange={v=>update({depth:Number(v),bottomDepth:Math.min(c.bottomDepth,Number(v))})}>{range.presets.map(d=><label key={d}><RadioGroupItem value={String(d)}/><span>{d} mm</span></label>)}</RadioGroup>
 {c.profile==='tapered'&&<NumberField label="Sill depth" min={50} max={c.depth} value={c.bottomDepth} onChange={v=>update({bottomDepth:v})} help="The side plates taper between head and sill."/>}
 {c.profile==='hood'&&<div className="hood-stiffeners"><h3>Hood stiffeners</h3><p className="inline-note">6 mm tapered plates above the canopy. First and last centres are 150 mm from each side; intermediate centres are equally spaced at 450 mm maximum.</p><NumberField label="Stiffener rear height" min={6} max={300} value={c.stiffenerHeight} onChange={v=>update({stiffenerHeight:v})} help="Tapers to zero at the front edge. 50 mm is the starting preview height."/><div className="stiffener-summary"><strong>{ribs.count} stiffeners</strong><span>{fmt(ribs.pitch)} mm equal centres</span></div><p className="field-help">Centres from left: {ribs.positions.map(fmt).join(' · ')} mm.</p><p className="inline-note">Window height is a reference only. The 6 mm canopy and stiffeners sit above this opening.</p></div>}
 {c.profile==='louvered'&&<><div className="field-grid"><NumberField label="Blade pitch" min={50} max={500} value={c.bladePitch} onChange={v=>update({bladePitch:v})}/><NumberField label="Blade angle" min={0} max={75} value={c.bladeAngle} onChange={v=>update({bladeAngle:v})}/></div><p className="inline-note">Blade arrangement is illustrative; openness and blade detail require confirmation.</p></>}
 </section>
 <section className="control-section"><div className="section-title"><span className="step">03</span><h2>Finish & fixing</h2></div>
 <div className="finish-label">Powder coat colour</div>
 <RadioGroup className="powder-swatches" aria-label="Powder coat colour" value={customColour?'':c.colour} onValueChange={v=>{const p=palette.find(p=>p.hex===v);if(p)update({colour:p.hex,finish:p.name,otherColour:''});}}>
 {palette.map(p=><label key={p.code} className="powder-option"><RadioGroupItem aria-label={p.name} value={p.hex} className="powder-radio"/><span aria-hidden="true" className="powder-chip" style={{backgroundColor:p.hex,backgroundImage:p.image?`url(${p.image})`:undefined}}>{!customColour&&c.colour===p.hex&&<Check size={16} style={{color:['Surfmist','Pearl White'].includes(p.name)?'#17202a':'#fff'}}/>}</span><span className="powder-name">{p.name}<small>{p.brand} · {p.sheen}</small></span></label>)}
 </RadioGroup>
 {!customColour&&<a className="colour-reference" href={selectedColour.source} target="_blank" rel="noreferrer">{selectedColour.brand} {selectedColour.code} · colour reference <ArrowUpRight size={13}/></a>}
 <label className="other-colour-field" htmlFor="other-colour"><span>Other</span><input id="other-colour" type="text" maxLength={120} value={c.otherColour} placeholder="Colour name or powder-coat code" aria-describedby="other-colour-help" onChange={e=>update({otherColour:e.target.value})}/></label>
 <p id="other-colour-help" className="field-help">{customColour?`Your custom colour request is saved in the specification. The preview remains ${c.finish} until a colour sample is confirmed.`:'Enter another colour to request it in your specification.'}</p>
 <p className="colour-disclaimer">Digital swatches and 3D lighting are indicative. Confirm the final finish with a physical sample.</p>
 <div className="finish-label">Rear fixing flange</div><RadioGroup className="flange-presets" aria-label="Rear fixing flange" value={String(c.flange)} onValueChange={v=>update({flange:Number(v)})}>{[0,50,100].map(v=><label key={v}><RadioGroupItem value={String(v)}/><span>{v===0?'None':`${v} mm`}</span></label>)}</RadioGroup><p className="field-help">{c.flange?`${fixings.points.length} fixing positions · up to ${fmt(fixings.maxPitch)} mm equal centres per run (250 mm maximum). Holes and screw sizes are illustrative.`:'Choose a flange to show fixing holes and screws.'}</p>
 </section></aside>
 <div className="results-column"><section className="viewer-card"><div className="viewer-toolbar"><Tabs value={tab} onValueChange={setTab}><TabsList className="view-tabs"><TabsTrigger value="3d"><Box size={16}/>3D view</TabsTrigger><TabsTrigger value="elevation"><Ruler size={16}/>Elevation</TabsTrigger></TabsList></Tabs><div className="viewer-switches"><label><Switch checked={dimensions} onCheckedChange={setDimensions} aria-label="Dimension labels"/><span>Dimensions</span></label><label><Switch checked={showWindow} onCheckedChange={setShowWindow} aria-label="Show window"/><span>Window</span></label></div></div>
 {tab==='3d'&&<div className="installation-toolbar"><div className="installation-switches"><label><Switch checked={showStudWall} onCheckedChange={setShowStudWall} aria-label="Show stud wall"/><span>Stud wall</span></label><label><Switch checked={showScrews} onCheckedChange={setShowScrews} disabled={!c.flange} aria-label="Show flange screws"/><span>Screws</span></label></div><span>{showStudWall?'90 × 45 mm pine · indicative framing':c.flange?'Hide screws to inspect flange holes':'No fixing flange selected'}</span></div>}
 <div className="stage" ref={stage}><div className="stage-title"><span>THERMACORE©</span><h2>{product.title}</h2></div><div className="material-chip"><Layers size={14}/>6 mm material</div>
 {tab==='3d'&&webgl?<ShroudView config={safe} windowVisible={showWindow} studWallVisible={showStudWall} screwsVisible={showScrews} dimensions={dimensions} view={view} reset={reset} onReady={onReady}/>:<Elevation config={safe}/>}
 {!webgl&&<div className="fallback-note">3D is unavailable on this device. Showing elevation.</div>}
 <div className="stage-bottom"><span><Move3d size={15}/>{tab==='3d'&&webgl?'Drag to rotate · Scroll or pinch to zoom':'FRONT ELEVATION · DIMENSIONS IN mm'}</span>{tab==='3d'&&<Button onClick={()=>{setView('perspective');setReset(n=>n+1);}} title="Reset camera" aria-label="Reset camera"><Maximize size={16}/></Button>}</div></div>
 <div className="view-footer">{tab==='3d'?<div className="camera-views" aria-label="Camera views">{(['perspective','front','side','top'] as ViewMode[]).map(v=><Button key={v} className={view===v?'active':''} onClick={()=>setView(v)}>{v==='perspective'?'Perspective':v[0].toUpperCase()+v.slice(1)}</Button>)}</div>:<span className="field-help">Nominal front profile · dimensions govern</span>}<Button variant="outline" className="button secondary view-download" disabled={!!errors.length||downloading} onClick={download}><Download size={15}/><span className="dl-label">{downloading?'Preparing PDF…':'Download configuration'}<span className="dl-sub"> (PDF)</span></span></Button></div>
 </section>
 <div className="metrics"><div><span>{c.profile==='corner'?'INTERNAL WIDTH A':c.profile==='hood'?'CLEAR CANOPY SPAN':c.profile==='round'?'INTERNAL DIAMETER':'INTERNAL WIDTH'}</span><strong>{fmt(c.width)}<small> mm</small></strong></div><div><span>{c.profile==='hood'?'WINDOW REFERENCE':c.profile==='round'?'INTERNAL RADIUS':'INTERNAL HEIGHT'}</span><strong>{fmt(c.profile==='round'?c.internalRadius:c.height)}<small> mm</small></strong></div><div><span>{c.profile==='tapered'?'HEAD DEPTH':'PROJECTION DEPTH'}</span><strong>{fmt(c.depth)}<small> mm</small></strong></div><div className="overall-metric"><span>{c.profile==='corner'?'INTERNAL RETURN B':c.profile==='hood'&&c.hoodCorner?'CORNER RETURN':c.profile==='round'?'OUTSIDE DIAMETER':'BODY OVERALL W × H'}</span><strong>{c.profile==='corner'||(c.profile==='hood'&&c.hoodCorner)?fmt(c.returnWidth):c.profile==='round'?fmt(m.outerWidth):`${fmt(m.outerWidth)} × ${fmt(m.outerHeight)}`}<small> mm</small></strong><small>{c.profile==='corner'||(c.profile==='hood'&&c.hoodCorner)?'90° external corner':'Excludes fixing flange'}</small></div></div>
 <section className="spec-card"><div className="spec-heading"><div className="section-title"><FileText size={19}/><h2>Your shroud specification</h2></div><span className="draft-badge">DESIGN DRAFT</span></div><div className="spec-content"><div className="spec-information"><label className="reference-field">Design reference<input aria-label="Design reference" maxLength={60} value={c.reference} onChange={e=>update({reference:e.target.value})}/></label><dl><div><dt>Profile</dt><dd>ThermaCore© {product.title}</dd></div>{hasPanelOptions(c.profile)&&<div><dt>Included panels</dt><dd>{panelDescription(c)}</dd></div>}<div><dt>Material thickness</dt><dd>6 mm</dd></div><div><dt>Drainage fall</dt><dd>{fallDescription(c)}</dd></div><div><dt>Powder coat colour</dt><dd>{finishSpec.finish}</dd></div>{customColour?<div><dt>Preview only</dt><dd>{c.finish}</dd></div>:<div><dt>Powder reference</dt><dd>{selectedColour.brand} {selectedColour.code} · {selectedColour.sheen}</dd></div>}<div><dt>Fixing flange</dt><dd>{c.flange?`${c.flange} mm`:'None'}</dd></div>{c.flange>0&&<div><dt>Fixing preview</dt><dd>{fixings.points.length} screws · ≤ {fmt(fixings.maxPitch)} mm centres</dd></div>}{c.profile==='tapered'&&<div><dt>Sill depth</dt><dd>{c.bottomDepth} mm</dd></div>}{['curved','round'].includes(c.profile)&&<div><dt>Internal radius</dt><dd>R {fmt(c.internalRadius)} mm</dd></div>}{c.profile==='round'&&<div><dt>Internal diameter</dt><dd>Ø {fmt(c.width)} mm</dd></div>}{c.profile==='hood'&&<><div><dt>Stiffeners</dt><dd>{ribs.count} × 6 mm plates</dd></div><div><dt>Rear height</dt><dd>{fmt(c.stiffenerHeight)} mm</dd></div><div><dt>End centres</dt><dd>150 mm from each side</dd></div><div><dt>Equal centres</dt><dd>{fmt(ribs.pitch)} mm</dd></div>{c.hoodCorner&&<div><dt>Corner return</dt><dd>{fmt(c.returnWidth)} mm{c.hoodCornerRounded?' · rounded':''}</dd></div>}</>}</dl></div><div className="spec-note"><Info size={18}/><p>All opening sizes are internal at the rear fixing plane. The 3D model shows nominal geometry. Pine framing and screw sizes are illustrative. Lintel sizing, drainage falls, joints and final fixing details are confirmed before manufacture.</p><Link to={`/products/${product.slug}`}>View product specification <ArrowUpRight size={14}/></Link></div></div></section>
 {errors.length>0&&<div role="alert" className="errors">{errors.join(' ')}</div>}
 </div></div><footer className="footer"><span>AUS WINDOW SHROUDS / SHROUD STUDIO</span><span>Designed around the opening.</span></footer></main>
 <section className={`print-sheet ${c.profile==='hood'?'hood-sheet':''}`}><div className="print-heading"><img src={builderAsset("aws-logo.svg")} alt="Aus Window Shrouds"/><div><h2>Shroud specification</h2><p>{c.reference||'Untitled design'} · Design draft</p></div></div><h2>ThermaCore© {product.title}</h2><div className="print-drawing"><Elevation config={c}/></div><table><tbody>{Object.entries(summary).filter(([k,v])=>v!==null&&k!=='note'&&k!=='previewColour').map(([k,v])=><tr key={k}><th>{k.replace(/([A-Z])/g,' $1').replace(/Mm$/,' (mm)')}</th><td>{String(v)}</td></tr>)}</tbody></table><p className="print-note">{summary.note} All opening measurements are internal. Overall dimensions exclude fixing flanges. Preview colours are indicative.</p></section>
  {notice&&<div role="status" className="toast"><Check size={17}/>{notice}</div>}</div><Footer />
 </>;
}
